server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/theft_detection_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # CORS Configuration
  web:
    cors:
      allowed-origins: "https://localhost:4200"
      allowed-methods: "*"
      allowed-headers: "*"

# File Storage Configuration
file:
  upload-dir: /workspace/uploads/
  max-size: 100MB

# WebSocket Configuration
websocket:
  endpoint: /ws
  allowed-origins: "https://localhost:4200"

logging:
  level:
    com.theftdetection: DEBUG
    org.springframework.web.socket: DEBUG